//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDV_Carlos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int id_cometario { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string respuesta { get; set; }
        public int id_usuario { get; set; }
        public int id_venta { get; set; }
        public int estatus { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
